# Generated by Django 2.0.7 on 2021-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210315_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summery',
            field=models.TextField(),
        ),
    ]
